version: '3'

services:
  latex:
    image: dxjoke/tectonic-docker
    command: tectonic -o /usr/src/tex/${COURSE} ${COURSE}/index.tex
    volumes:
      - ./${COURSE}:/usr/src/tex/${COURSE}
      - ./preamble.tex:/usr/src/tex/preamble.tex
